# Site settings
title: Neural Convolutions
description: "Blog about Neural Networks"
url: "http://neural-convolutions.net"
author:
  name: "Ondrej Zapletal"
  email: "ondrej.zapletal@neural-convolutions.net"
  url: "http://neural-convolutions.net"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: _site
permalink: /:title
paginate: 5
paginate_path: /page:num/


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

gems: [jekyll-paginate]
